### ISSUE TITLE
Having an error message  'Ballerina only supports local reference values'

### ISSUE THREAD

**Issue by SanduDS** [ballerina-platform/ballerina-openapi#568]
**Description:**
Having the following error for [this openAPI file](https://api-docs.beezup.com/swagger.json).
The error message: 
````
Invalid reference value : BeezUP.Common.UserErrorMessage_arguments
Ballerina only supports local reference values.
````

**Steps to reproduce:**
Generate client connector using the above swagger file

**OS, DB, other environment details and versions:**
Ubuntu, Ballerina Swan Lake Beta2

**Comment by SanduDS** [comment]
I checked and found out this error message is for invalid record type names like **Abc.def**. However, when we remove period symbols, the connector is generated.

However, We might provide a separate improvement as follows.
#### Invalid ballerina type name:
```ballerina
public type 'Beezup.Common.Successsummary record {
```
#### Suggestion
Valid ballerina type name
```ballerina
public type 'Beezup\.Common\.Successsummary record {
```

**Comment by aneeshafedo** [comment]
This turns out to be an issue with the flattened OpenAPI file.  

> I checked and found out this error message is for invalid record type names like **Abc.def**. However, when we remove period symbols, the connector is generated.
> 
> However, We might provide a separate improvement as follows.
> 
> #### Invalid ballerina type name:
> ```ballerina
> public type 'Beezup.Common.Successsummary record {
> ```
> 
> #### Suggestion
> Valid ballerina type name
> 
> ```ballerina
> public type 'Beezup\.Common\.Successsummary record {
> ```

In the process of record generation we remove special characters from a given schema name and generate a valid type name in which `BeezUP.Common.UserErrorMessage_arguments` should be converted to `BeezUPCommonUserErrorMessageArguments` removing full stop symbols. The reported error message `Ballerina only supports local reference values` returns from [here](https://github.com/ballerina-platform/ballerina-openapi/blob/462cb8dd0f24ba1d1c0a31c94dc3e5659d944326/openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorUtils.java#L324) when trying to extract the name of the referenced schema from the reference path. 

This error is due to a bug in swagger OpenAPI parser when trying to flatten the inline schema inside `BeezUP.Common.UserErrorMessage` schema. After flattening the path to the schema has changed to `$ref: BeezUP.Common.UserErrorMessage_arguments` omitting the `#/components/schemas` section. Without the full path to the schema `#/components/schemas\BeezUP.Common.UserErrorMessage_arguments` we cannot extract the referenced schema name and that return the above error.
